security:
    enable_authenticator_manager: true

    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Define your user provider (you may have additional providers here)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Define your custom authenticator (you may have different authenticators)
            custom_authenticator: App\Security\AdminAuthenticator

            logout:
                path: app_logout
                # You can specify where to redirect after logout here
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # Define access control rules for your routes
        # Add more rules as needed
        - { path: ^/item/delete/\d+, roles: ROLE_USER } # Allow ROLE_USER to access item_delete with any ID

# Configuration for when running tests
# Adjust these settings as needed for your test environment
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
