vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        Item:
            uri_prefix: /images/Item
            upload_destination: '%kernel.project_dir%/public/images/Item'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer